api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: 'API Lior Tuto'
    description: 'API avec des clients -> factures relié à des utilisateurs.'
    collection:
        pagination:
            enabled: false
            items_per_page: 15